In [13]:
import pandas as pd
df1 = pd.DataFrame({
    'Employee_ID': [101,102,103,104,105],
    'Employee_name':['AA','BB','CC','DD','EE']
})
df1

   Employee_ID Employee_name
0          101            AA
1          102            BB
2          103            CC
3          104            DD
4          105            EE

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)

2

In [14]:
import pandas as pd
df2 = pd.DataFrame({
    'Employee_ID': [101,103,104,105,106],
    'Project_name':['A','B','C','D','E']
})
df2

   Employee_ID Project_name
0          101            A
1          103            B
2          104            C
3          105            D
4          106            E

Inner Join

In [ ]:
import pandas as pd
results = pd.merge(df1,df2, on ='Employee_ID', how='inner')
results

   Employee_ID Employee_name Project_name
0          101            AA            A
1          103            CC            B
2          104            DD            C
3          105            EE            D

Outer Join

In [16]:
import pandas as pd
results = pd.merge(df1,df2, on ='Employee_ID', how='outer')
results

   Employee_ID Employee_name Project_name
0          101            AA            A
1          102            BB          NaN
2          103            CC            B
3          104            DD            C
4          105            EE            D
5          106           NaN            E

Left Join

In [6]:
import pandas as pd
results = pd.merge(df1,df2, on ='Employee_ID', how='left')
results

   Employee_ID Employee_name Project_name
0          101            AA            A
1          102            BB          NaN
2          103            CC            B
3          104            DD            C
4          105            EE            D

In [7]:
import pandas as pd
results = pd.merge(df1,df2, on ='Employee_ID', how='right')
results

   Employee_ID Employee_name Project_name
0          101            AA            A
1          103            CC            B
2          104            DD            C
3          105            EE            D
4          106           NaN            E

In [8]:
df1 = pd.DataFrame({'Name':['A', 'B', 'C']})
df2 = pd.DataFrame({'ID':['1', '2', '3']})
df1

  Name
0    A
1    B
2    C

In [9]:
df2

  ID
0  1
1  2
2  3

In [17]:
results = pd.merge(df1,df2,how='cross')
results

    Employee_ID_x Employee_name  Employee_ID_y Project_name
0             101            AA            101            A
1             101            AA            103            B
2             101            AA            104            C
3             101            AA            105            D
4             101            AA            106            E
5             102            BB            101            A
6             102            BB            103            B
7             102            BB            104            C
8             102            BB            105            D
9             102            BB            106            E
10            103            CC            101            A
11            103            CC            103            B
12            103            CC            104            C
13            103            CC            105            D
14            103            CC            106            E
15            104            DD            101            A
16            104            DD            103            B
17            104            DD            104            C
18            104            DD            105            D
19            104            DD            106            E
20            105            EE            101            A
21            105            EE            103            B
22            105            EE            104            C
23            105            EE            105            D
24            105            EE            106            E